name: ci-checks

on:
  push:
    branches:
      - main
      - master
  pull_request:
  workflow_dispatch:

jobs:

  Checks:
  
    runs-on: ubuntu-latest

    env:
      LABVIEW_VERSION_NUMBER: '20.1'
      LABVIEW_VERSION_YEAR: '2020'
      LABVIEW_BITNESS: '64'

    steps:

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          # cache: 'pip'
          

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install pylavi
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv venv
          uv pip install pylavi

      - name: Run pylavi Tests
        run: |
          echo running pylavi tests
          source .venv/bin/activate
          vi_validate \
            --path source \
            --path tests \
            --gt 20 --lt 21 \
            --skip *.vit \
            --no-code \
            --breakpoints
          echo finished pylavi tests

  Build:

    runs-on: ubuntu-latest

    container:
      image: nationalinstruments/labview:2025q3patch1-linux

    env:
      VIPM_SERIAL_NUMBER: ${{ secrets.VIPM_SERIAL_NUMBER }}
      VIPM_FULL_NAME: ${{ secrets.VIPM_FULL_NAME }}
      VIPM_EMAIL: ${{ secrets.VIPM_EMAIL }}

    steps:
      
      - name: Install prerequisites
        run: apt-get update && apt-get install -y wget
      
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache VIPM packages
        uses: actions/cache@v4
        with:
          path: |
            /usr/local/natinst/LabVIEW*/
            /usr/local/jki/vipm/cache/
            /usr/local/jki/vipm/db/
          key: ${{ runner.os }}-vipm-${{ hashFiles('project.vipc') }}

      - name: Install VIPM
        run: |
          wget -O vipm.deb https://packages.jki.net/vipm/preview/vipm_latest_preview_amd64.deb
          dpkg -i vipm.deb
          rm vipm.deb

      - name: Activate VIPM
        run: |
          vipm vipm-activate --serial-number "${{ env.VIPM_SERIAL_NUMBER }}" --name "${{ env.VIPM_FULL_NAME }}" --email "${{ env.VIPM_EMAIL }}"

      - name: Refresh package list
        run: vipm package-list-refresh

      - name: Install project dependencies
        run: vipm install --labview-version 2025 source/.vipc

      - name: Build package
        run: vipm build --labview-version 2025 source/.vipb

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: built-package
          path: |
            *.vip

